require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const pool = require('./config/db');
const app = express();
const PORT = process.env.PORT || 5000;
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/products', require('./routes/productRoutes'));
app.use('/api/customers', require('./routes/customerRoutes'));
app.use('/api/orders', require('./routes/orderRoutes'));
app.use('/api/riders', require('./routes/riderRoutes'));
app.use('/api/cash', require('./routes/cashRoutes'));
app.use('/api/users',     require('./routes/userRoutes'));
app.use('/api/password',  require('./routes/passwordResetRoutes'));
app.use('/api/inventory', require('./routes/inventoryRoutes'));
app.use('/api/payments', require('./routes/paymentRoutes'));
app.use('/api/reports', require('./routes/reportRoutes'));
app.get('/', (req, res) => { res.json({ success: true, message: 'Pro Cyclone API is running 🚀', version: '1.0.0' }); });
app.get('/health', async (req, res) => { try { await pool.query('SELECT NOW()'); res.json({ success: true, message: 'Server and database are healthy ✅' }); } catch (error) { res.status(500).json({ success: false, message: 'Database connection failed ❌' }); } });
process.on('uncaughtException', (err) => { console.error('Uncaught Exception:', err); });
process.on('unhandledRejection', (err) => { console.error('Unhandled Rejection:', err); });
app.listen(PORT, async () => { console.log(`🚀 Pro Cyclone server running on port ${PORT}`); try { await pool.query('SELECT NOW()'); console.log('✅ Database connected successfully'); } catch (err) { console.error('❌ Database connection failed:', err.message); } });
