require('dotenv').config();
const express = require('express');
const http = require('http');
const { Server } = require('socket.io');
const setupSocket = require('./socketSetup');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const pool = require('./config/db');
const app = express();
const server = http.createServer(app);
const io = new Server(server, {
  cors: { origin: process.env.ALLOWED_ORIGINS?.split(',') || ['http://localhost:3000'], credentials: true },
});
setupSocket(io);
const PORT = process.env.PORT || 5000;
app.use(helmet());
app.use(cors());
app.use(morgan('dev'));
app.use(express.json({
  verify: (req, res, buf) => { req.rawBody = buf; }
}));
app.use(express.urlencoded({ extended: true }));
app.use('/api/auth', require('./routes/authRoutes'));
app.use('/api/products', require('./routes/productRoutes'));
app.use('/api/customers', require('./routes/customerRoutes'));
app.use('/api/orders', require('./routes/orderRoutes'));
app.use('/api/riders', require('./routes/riderRoutes'));
app.use('/api/cash', require('./routes/cashRoutes'));
app.use('/api/users',     require('./routes/userRoutes'));
app.use('/api/password',  require('./routes/passwordResetRoutes'));
app.use('/api/inventory', require('./routes/inventoryRoutes'));
app.use('/api/restock-requests', require('./routes/restockRoutes'));
app.use('/api/scheduler', require('./routes/schedulerRoutes'));
app.use('/api/payments', require('./routes/paymentRoutes'));
app.use('/api/returns', require('./routes/returnRoutes'));
app.use('/api/business-profile', require('./routes/businessProfileRoutes'));
app.use('/api/delivery-zones', require('./routes/deliveryZoneRoutes'));
app.use('/api/pricing-settings', require('./routes/pricingSettingsRoutes'));
app.use('/api/rbac', require('./routes/rbacRoutes'));
app.use('/api/expenses', require('./routes/expenseRoutes'));
app.use('/api/reports', require('./routes/reportRoutes'));
app.use('/api/settings', require('./routes/settings'));
app.use('/api/surcharge-rules', require('./routes/surchargeRuleRoutes'));
app.use('/api/discount-rules', require('./routes/discountRuleRoutes'));
app.use('/api/settlements', require('./routes/settlementRoutes'));
app.use('/api/imports', require('./routes/importRoutes'));
app.use('/api/compliance', require('./routes/complianceRoutes'));
app.use('/api/quick-links', require('./routes/quickLinksRoutes'));
app.use('/api/notifications', require('./routes/notifications'));
app.use('/api/whatsapp', require('./routes/whatsapp'));
app.use('/api/telegram', require('./routes/telegram'));
app.use('/api/chat', require('./routes/chat'));
app.use('/api/hr', require('./routes/hr'));
app.use('/api/webhooks', require('./routes/webhookRoutes'));
app.get('/', (req, res) => { res.json({ success: true, message: 'Pro Cyclone API is running 🚀', version: '1.0.0' }); });
app.get('/health', async (req, res) => { try { await pool.query('SELECT NOW()'); res.json({ success: true, message: 'Server and database are healthy ✅' }); } catch (error) { res.status(500).json({ success: false, message: 'Database connection failed ❌' }); } });
process.on('uncaughtException', (err) => { console.error('Uncaught Exception:', err); });
process.on('unhandledRejection', (err) => { console.error('Unhandled Rejection:', err); });
server.listen(PORT, async () => { console.log(`🚀 Pro Cyclone server running on port ${PORT}`); try { await pool.query('SELECT NOW()'); console.log('✅ Database connected successfully'); } catch (err) { console.error('❌ Database connection failed:', err.message); } });
